export {default as profile1} from "./profile-1.png"
export {default as profile2} from "./profile-2.jpg"
export {default as profile3} from "./profile-3.jpeg"
export {default as profile4} from "./profile-4.jpeg"
export {default as profile5} from "./profile-5.jpeg"
export {default as profile6} from "./profile-6.jpeg"