export {default as profile1} from "./profile-1.png"
export {default as sharukhPhoto} from "./sharukh_photo.png"
export {default as spotifyThumbnail} from "./spotify-thumbnail.png"
export {default as memorygameThumbnail} from "./memorygame-thumbnail.png"
export {default as ui_ux_design} from "./ui_ux_desin.png"
export {default as ecommerce} from "./Ecommerce.png"    